In [2]:
import json
import pandas as pd

In [4]:
df = pd.read_parquet("data/train.parquet")

In [2]:
df

,sent_id,text,comments,tokens,lemmas,upos,xpos,feats,head,deprel,deps,misc,mwt,empty_nodes
0,2003Anketa.xml_1,Анкета.,"[__SENT_ID__, __TEXT__]","[Анкета, .]","[анкета, .]","[NOUN, PUNCT]","[None, None]","[Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing,...","[0, 1]","[root, punct]","[0:root, 1:punct]","[SpaceAfter=No, None]",[],[]
1,2003Anketa.xml_2,Начальник областного управления связи Семен Ер...,"[__SENT_ID__, __TEXT__]","[Начальник, областного, управления, связи, Сем...","[начальник, областной, управление, связь, Семе...","[NOUN, ADJ, NOUN, NOUN, PROPN, PROPN, AUX, NOU...","[None, None, None, None, None, None, None, Non...",[Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing...,"[8, 3, 1, 3, 1, 5, 8, 0, 8, 11, 8, 13, 11, 11,...","[nsubj, amod, nmod, nmod, appos, flat:name, co...","[8:nsubj, 3:amod, 1:nmod:gen, 3:nmod:gen, 1:ap...","[None, None, None, None, None, None, None, Non...",[],[]
2,2003Anketa.xml_3,"В приемной его с утра ожидали посетители, - ко...","[__SENT_ID__, __TEXT__]","[В, приемной, его, с, утра, ожидали, посетител...","[в, приемная, он, с, утро, ожидать, посетитель...","[ADP, NOUN, PRON, ADP, NOUN, VERB, NOUN, PUNCT...","[None, None, None, None, None, None, None, Non...","[None, Animacy=Inan|Case=Loc|Gender=Fem|Number...","[2, 6, 6, 5, 6, 0, 6, 13, 13, 13, 13, 13, 7, 1...","[case, obl, obj, case, obl:tmod, root, nsubj, ...","[2:case, 6:obl:в:loc, 6:obj, 5:case, 6:obl:с:g...","[None, None, None, None, None, None, SpaceAfte...",[],[]
3,2003Anketa.xml_4,Однако стиль работы Семена Еремеевича заключал...,"[__SENT_ID__, __TEXT__]","[Однако, стиль, работы, Семена, Еремеевича, за...","[однако, стиль, работа, Семен, Еремеевич, закл...","[ADV, NOUN, NOUN, PROPN, PROPN, VERB, ADP, PRO...","[None, None, None, None, None, None, None, Non...","[Degree=Pos, Animacy=Inan|Case=Nom|Gender=Masc...","[6, 6, 2, 3, 4, 0, 8, 6, 11, 11, 8, 13, 11, 16...","[advmod, nsubj, nmod, nmod, flat:name, root, c...","[6:advmod, 6:nsubj, 2:nmod:gen, 3:nmod:gen, 4:...","[None, None, None, None, None, None, None, Spa...",[],[]
4,2003Anketa.xml_5,"Приемная была обставлена просто, но по-деловому.","[__SENT_ID__, __TEXT__]","[Приемная, была, обставлена, просто, ,, но, по...","[приемная, быть, обставить, просто, ,, но, по-...","[NOUN, AUX, VERB, ADV, PUNCT, CCONJ, ADV, PUNCT]","[None, None, None, None, None, None, None, None]","[Animacy=Inan|Case=Nom|Gender=Fem|Number=Sing,...","[3, 3, 0, 3, 7, 7, 4, 3]","[nsubj:pass, aux:pass, root, advmod, punct, cc...","[3:nsubj:pass, 3:aux:pass, 0:root, 3:advmod, 7...","[None, None, None, SpaceAfter=No, None, None, ...",[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69626,2020_RFFITrudnosti_ponimaniya.xml_234,"Благодаря расширению контактов, возможностям, ...","[Added to SynTagRus 2015–2020., __SENT_ID__, g...","[Благодаря, расширению, контактов, ,, возможно...","[благодаря, расширение, контакт, ,, возможност...","[ADP, NOUN, NOUN, PUNCT, NOUN, PUNCT, VERB, AD...","[None, None, None, None, None, None, None, Non...","[None, Animacy=Inan|Case=Dat|Gender=Neut|Numbe...","[2, 32, 2, 5, 2, 7, 5, 10, 10, 7, 10, 13, 2, 1...","[case, obl, nmod, punct, conj, punct, acl, amo...","[2:case, 32:obl:благодаря:dat, 2:nmod:gen, 5:p...","[None, None, SpaceAfter=No, None, SpaceAfter=N...",[],[]
69627,2020_RFFITrudnosti_ponimaniya.xml_235,На современном этапе итальянско-российские отн...,"[Added to SynTagRus 2015–2020., __SENT_ID__, g...","[На, современном, этапе, итальянско, -, россий...","[на, современный, этап, итальянско, -, российс...","[ADP, ADJ, NOUN, ADJ, PUNCT, ADJ, NOUN, ADP, N...","[None, None, None, None, None, None, None, Non...","[None, Case=Loc|Degree=Pos|Gender=Masc|Number=...","[3, 3, 16, 6, 4, 7, 16, 9, 7, 12, 10, 13, 9, 1...","[case, amod, obl, compound, punct, amod, nsubj...","[3:case, 3:amod, 16:obl:на:loc, 6:compound, 4:...","[None, None, None, SpaceAfter=No, SpaceAfter=N...",[],[]
69628,2020_RFFITrudnosti_ponimaniya.xml_236,"Этому способствуют и известная отстраненность,...","[Added to SynTagRus 2015–2020., __SENT_ID__, g...","[Этому, способствуют, и, известная, отстраненн...","[это, способствовать, и, известный, отстраненн...","[PRON, VERB, PART, ADJ, NOUN, PUNCT, VERB, ADJ...","[None, None, None, None, None, None, None, Non...",[Animacy=Inan|Case=Dat|Gender=Neut|Number=Sing...,"[2, 0, 5, 5, 2, 7, 5, 9, 7, 13, 12, 13, 7, 13,...","[iobj, root, advmod, amod, nsubj, punct, acl, ...","[2:iobj, 0:root, 5:advmod, 5:amod, 2:nsubj, 7:...","[None, None, None, None, SpaceAfter=No, None, ...",[],[]
69629,2020_RFFITrudnosti_ponimaniya.xml_237,В XXI столетии итальянская и российская общест...,"[Added to SynTagRus 2015–2020., __SENT_ID__, g...","[В, XXI, столетии, итальянская, и, российская,...","[в, XXI, столетие, итальянский, и, российский,...","[ADP, ADJ, NOUN, ADJ, CCONJ, ADJ, NOUN, PUNCT,...","[None, None, None, None, None, None, None, Non...","[None, NumForm=Roman|NumType=Ord, Animacy=Inan...","[3, 3, 11, 7, 6, 4, 11, 9, 11, 9, 0, 11, 12, 1...","[case, amod, obl:tmod, amod, cc, conj, nsubj:p...","[3:case, 3:amod, 11:obl:в:loc, 7:amod, 6:cc, 4...","[None, None, None, None, None, None, SpaceAfte...",[],[]
69630,2020_RFFITrudnosti_ponimaniya.xml_238,"И в этих условиях важнейшей сферой, где ""имидж...","[Added to SynTagRus 2015–2020., __SENT_ID__, g...","[И, в, этих, условиях, важнейшей, сферой, ,, г...","[и, в, этот, условие, важнейший, сфера, ,, где...","[CCONJ, ADP, DET, NOUN, ADJ, NOUN, PUNCT, ADV,...","[None, None, None, None, None, None, None, Non...","[None, None, Case=Loc|Number=Plur|PronType=Dem...","[17, 4, 4, 17, 6, 17, 13, 13, 10, 13, 10, 10, ...","[cc, case, det, obl, amod, xcomp, punct, advmo...","[17:cc, 4:case, 4:det, 17:obl:в:loc, 6:amod, 1...","[None, None, None, None, None, SpaceAfter=No, ...",[],[]

In [15]:
exdf = df[["tokens", "lemmas", "upos"]].copy()
exdf

,tokens,lemmas,upos
0,"[Анкета, .]","[анкета, .]","[NOUN, PUNCT]"
1,"[Начальник, областного, управления, связи, Сем...","[начальник, областной, управление, связь, Семе...","[NOUN, ADJ, NOUN, NOUN, PROPN, PROPN, AUX, NOU..."
2,"[В, приемной, его, с, утра, ожидали, посетител...","[в, приемная, он, с, утро, ожидать, посетитель...","[ADP, NOUN, PRON, ADP, NOUN, VERB, NOUN, PUNCT..."
3,"[Однако, стиль, работы, Семена, Еремеевича, за...","[однако, стиль, работа, Семен, Еремеевич, закл...","[ADV, NOUN, NOUN, PROPN, PROPN, VERB, ADP, PRO..."
4,"[Приемная, была, обставлена, просто, ,, но, по...","[приемная, быть, обставить, просто, ,, но, по-...","[NOUN, AUX, VERB, ADV, PUNCT, CCONJ, ADV, PUNCT]"
...,...,...,...
69626,"[Благодаря, расширению, контактов, ,, возможно...","[благодаря, расширение, контакт, ,, возможност...","[ADP, NOUN, NOUN, PUNCT, NOUN, PUNCT, VERB, AD..."
69627,"[На, современном, этапе, итальянско, -, россий...","[на, современный, этап, итальянско, -, российс...","[ADP, ADJ, NOUN, ADJ, PUNCT, ADJ, NOUN, ADP, N..."
69628,"[Этому, способствуют, и, известная, отстраненн...","[это, способствовать, и, известный, отстраненн...","[PRON, VERB, PART, ADJ, NOUN, PUNCT, VERB, ADJ..."
69629,"[В, XXI, столетии, итальянская, и, российская,...","[в, XXI, столетие, итальянский, и, российский,...","[ADP, ADJ, NOUN, ADJ, CCONJ, ADJ, NOUN, PUNCT,..."
69630,"[И, в, этих, условиях, важнейшей, сферой, ,, г...","[и, в, этот, условие, важнейший, сфера, ,, где...","[CCONJ, ADP, DET, NOUN, ADJ, NOUN, PUNCT, ADV,..."

In [ ]:
exdf["tokens"] = exdf["tokens"].apply(
    lambda arr: [s.replace("ё", "е").replace("Ё", "Е") for s in arr]
)
exdf["lemmas"] = exdf["lemmas"].apply(
    lambda arr: [s.lower().replace("ё", "е").replace("Ё", "Е") for s in arr]
)

In [36]:
symbs = "йцукенгшщзхъфывапролджэячсмитьбю"
symbs += symbs.upper()
symbs += ".,?!1234567890"
symbs = set(symbs)

In [37]:
def filter_triple(tokens, lemmas, upos):
    nt, nl, nu = [], [], []
    for t, l, u in zip(tokens, lemmas, upos):
        if not symbs.isdisjoint(t):
            nt.append(t)
            nl.append(l)
            nu.append(u)
    return nt, nl, nu


res = [
    filter_triple(t, l, u)
    for t, l, u in zip(exdf["tokens"], exdf["lemmas"], exdf["upos"])
]
exdf["tokens"], exdf["lemmas"], exdf["upos"] = map(list, zip(*res))

In [ ]:
exdf.to_pickle("data/train.pcl")

In [ ]:
chars = set(''.join(exdf["tokens"].explode().dropna()))
chars = list(chars)
chars = ["<PAD>", "<UNK>", "<SOS>", "<EOS>"] + chars
with open("data/char2id.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(chars, list(range(len(chars))))), f, ensure_ascii=False)

words = exdf["tokens"].explode().value_counts()
words = ["<PAD>", "<UNK>"] + list(words[words >= 3].index)
with open("data/word2id.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(words, list(range(len(words))))), f, ensure_ascii=False)

In [65]:
with open("data/char2id.json", "r", encoding="utf-8") as f:
    char2id = json.load(f)
with open("data/id2char.json", "x", encoding="utf-8") as f:
    json.dump({v: k for k, v in char2id.items()}, f, ensure_ascii=False)

In [23]:
exdf = pd.read_parquet("data/train.parquet")[["tokens", "lemmas", "upos"]].copy()

In [15]:
symbs = "йцукенгшщзхъфывапролджэячсмитьбю"
symbs += symbs.upper()
symbs += "1234567890"
symbs = set(symbs)
symbs.issuperset("ежик")

True

In [ ]:
def preprocessing(dataframe):
    df = dataframe.copy()
    df["tokens"] = df["tokens"].apply(
        lambda arr: [s.replace("ё", "е").replace("Ё", "Е") for s in arr]
    )
    df["lemmas"] = df["lemmas"].apply(
        lambda arr: [s.lower().replace("ё", "е").replace("Ё", "Е") for s in arr]
    )
    symbs = "йцукенгшщзхъфывапролджэячсмитьбю"
    symbs += symbs.upper()
    symbs += "1234567890"
    symbs = set(symbs)
    def filter_triple(tokens, lemmas, upos):
        nonlocal symbs
        nt, nl, nu = [], [], []
        for t, l, u in zip(tokens, lemmas, upos):
            if symbs.issuperset(t):
                nt.append(t)
                nl.append(l)
                nu.append(u)
        return nt, nl, nu


    res = [
        filter_triple(t, l, u)
        for t, l, u in zip(df["tokens"], df["lemmas"], df["upos"])
    ]
    df["tokens"], df["lemmas"], df["upos"] = map(list, zip(*res))
    return df

In [27]:
preprocessing(exdf).to_pickle("data/train_prepr.pcl")

In [29]:
exdf = pd.read_pickle("data/train_prepr.pcl")
chars = set(''.join(exdf["tokens"].explode().dropna()))
chars = list(chars)
chars = ["<PAD>", "<UNK>", "<SOS>", "<EOS>"] + chars
with open("data/char2id.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(chars, list(range(len(chars))))), f, ensure_ascii=False)

words = exdf["tokens"].explode().value_counts()
words = ["<PAD>", "<UNK>"] + list(words[words >= 2].index)
with open("data/word2id.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(words, list(range(len(words))))), f, ensure_ascii=False)

with open("data/char2id.json", "r", encoding="utf-8") as f:
    char2id = json.load(f)
with open("data/id2char.json", "w", encoding="utf-8") as f:
    json.dump({v: k for k, v in char2id.items()}, f, ensure_ascii=False)

In [66]:
s = exdf.upos.explode()
bad = s[s.isna()]
print(bad)
print(exdf.loc[bad.index, "upos"])

803      NaN
3792     NaN
4141     NaN
4155     NaN
4156     NaN
4162     NaN
4396     NaN
5426     NaN
8293     NaN
14991    NaN
19564    NaN
24664    NaN
27181    NaN
28419    NaN
56269    NaN
57864    NaN
63009    NaN
63372    NaN
63407    NaN
63473    NaN
63520    NaN
63582    NaN
63636    NaN
63657    NaN
63737    NaN
63803    NaN
63854    NaN
63967    NaN
63995    NaN
64009    NaN
64054    NaN
64115    NaN
64188    NaN
64279    NaN
64296    NaN
64357    NaN
64373    NaN
64390    NaN
64409    NaN
64553    NaN
64577    NaN
64588    NaN
64644    NaN
64720    NaN
64879    NaN
65792    NaN
66799    NaN
Name: upos, dtype: object
803      []
3792     []
4141     []
4155     []
4156     []
4162     []
4396     []
5426     []
8293     []
14991    []
19564    []
24664    []
27181    []
28419    []
56269    []
57864    []
63009    []
63372    []
63407    []
63473    []
63520    []
63582    []
63636    []
63657    []
63737    []
63803    []
63854    []
63967    []
63995    []
64009    []
64054    []
64115    []
64188    []
64279    []
64296    []
64357    []
64373    []
64390    []
64409    []
64553    []
64577    []
64588    []
64644    []
64720    []
64879    []
65792    []
66799    []
Name: upos, dtype: object

In [67]:
exdf.drop(index=bad.index, inplace=True)

In [68]:
s = exdf.upos.explode()
bad = s[s.isna()]
print(bad)
print(exdf.loc[bad.index, "upos"])

Series([], Name: upos, dtype: object)
Series([], Name: upos, dtype: object)

In [69]:
exdf.to_pickle("data/train_prepr.pcl")

In [16]:
exdf = pd.read_pickle("data/train_prepr.pcl")
exdf["tokens"] = exdf["tokens"].apply(
    lambda arr: [s.lower() for s in arr]
)
exdf.to_pickle("data/train_prepr.pcl")
chars = set(''.join(exdf["tokens"].explode().dropna()))
chars = list(chars)
chars = ["<PAD>", "<UNK>", "<SOS>", "<EOS>"] + chars
with open("data/char2id.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(chars, list(range(len(chars))))), f, ensure_ascii=False)

words = exdf["tokens"].explode().value_counts()
words = ["<PAD>", "<UNK>"] + list(words[words >= 2].index)
with open("data/word2id.json", "w", encoding="utf-8") as f:
    json.dump(dict(zip(words, list(range(len(words))))), f, ensure_ascii=False)

with open("data/char2id.json", "r", encoding="utf-8") as f:
    char2id = json.load(f)
with open("data/id2char.json", "w", encoding="utf-8") as f:
    json.dump({v: k for k, v in char2id.items()}, f, ensure_ascii=False)

validation

In [30]:
valdf = pd.read_parquet("data/dev.parquet")
valdf = valdf[["tokens", "lemmas", "upos"]].copy()
valdf = preprocessing(valdf)
valdf.to_pickle("data/val_prepr.pcl")

In [32]:
pd.read_pickle("data/val_prepr.pcl")

,tokens,lemmas,upos
0,"[Алгоритм, от, имени, ученого, аль, Хорезми, т...","[алгоритм, от, имя, ученый, аль, хорезми, точн...","[NOUN, ADP, NOUN, NOUN, PART, PROPN, ADJ, NOUN..."
1,"[В, старой, трактовке, вместо, слова, порядок,...","[в, старый, трактовка, вместо, слово, порядок,...","[ADP, ADJ, NOUN, ADP, NOUN, NOUN, VERB, NOUN, ..."
2,"[Это, связано, с, тем, что, работа, инструкций...","[это, связать, с, то, что, работа, инструкция,...","[PRON, VERB, ADP, PRON, SCONJ, NOUN, NOUN, NOU..."
3,"[Таким, образом, некоторые, инструкции, должны...","[такой, образ, некоторый, инструкция, должен, ...","[DET, NOUN, DET, NOUN, ADJ, VERB, ADV, ADP, NO..."
4,"[Независимые, инструкции, или, инструкции, ста...","[независимый, инструкция, или, инструкция, ста...","[ADJ, NOUN, CCONJ, NOUN, VERB, ADJ, NOUN, NOUN..."
...,...,...,...
8901,"[Да, я, не, догадывался, что, восприятие, живо...","[да, я, не, догадываться, что, восприятие, жив...","[PART, PRON, PART, VERB, SCONJ, NOUN, ADJ, ADJ..."
8902,"[Но, всякий, кто, выступает, перед, аудиторией...","[но, всякий, кто, выступать, перед, аудитория,...","[CCONJ, DET, PRON, VERB, ADP, NOUN, ADJ, AUX, ..."
8903,[Любое],[любой],[DET]
8904,"[Тем, более, выраженное, столь, явно]","[то, более, выразить, столь, явно]","[PRON, ADV, VERB, ADV, ADV]"
8905,"[В, наши, дни, когда, никто, никого, не, слуша...","[в, наш, день, когда, никто, никто, не, слушат...","[ADP, DET, NOUN, ADV, PRON, PRON, PART, VERB, ..."

In [70]:
valdf = pd.read_pickle("data/val_prepr.pcl")
s = valdf.upos.explode()
bad = s[s.isna()]
print(bad)
print(valdf.loc[bad.index, "upos"])

426     NaN
505     NaN
7273    NaN
7723    NaN
8298    NaN
8435    NaN
8619    NaN
8783    NaN
Name: upos, dtype: object
426     []
505     []
7273    []
7723    []
8298    []
8435    []
8619    []
8783    []
Name: upos, dtype: object

In [71]:
valdf.drop(index=bad.index, inplace=True)
s = valdf.upos.explode()
bad = s[s.isna()]
print(bad)
print(valdf.loc[bad.index, "upos"])

Series([], Name: upos, dtype: object)
Series([], Name: upos, dtype: object)

In [72]:
valdf.to_pickle("data/val_prepr.pcl")

In [17]:
valdf = pd.read_pickle("data/val_prepr.pcl")
valdf["tokens"] = valdf["tokens"].apply(
    lambda arr: [s.lower() for s in arr]
)
valdf.to_pickle("data/val_prepr.pcl")

test

In [73]:
testdf = pd.read_parquet("data/test.parquet")
testdf = testdf[["tokens", "lemmas", "upos"]]
testdf = preprocessing(testdf)
s = testdf.upos.explode()
bad = s[s.isna()]
testdf.drop(index=bad.index, inplace=True)
s = testdf.upos.explode()
bad = s[s.isna()]
print(bad)
print(testdf.loc[bad.index, "upos"])

Series([], Name: upos, dtype: object)
Series([], Name: upos, dtype: object)

In [75]:
testdf.to_pickle("data/test_prepr.pcl")

In [18]:
testdf = pd.read_pickle("data/test_prepr.pcl")
testdf["tokens"] = testdf["tokens"].apply(
    lambda arr: [s.lower() for s in arr]
)
testdf.to_pickle("data/test_prepr.pcl")

In [19]:
exdf.shape, valdf.shape, testdf.shape

((69584, 3), (8898, 3), (8796, 3))